#!/usr/bin/env python3
"""
Healthcare Data Population Script

Reads synthetic JSON files generated by module-5 generators and
uploads them to DynamoDB.

Usage:
    python populate-healthcare-data.py \
        --json-file ../module-5-synthetic-data/datasets/patient-health/synthetic_patients.json \
        --type patient \
        --profile uo-innovation

    python populate-healthcare-data.py \
        --json-file ../module-5-synthetic-data/datasets/dental-records/synthetic_dental_visits.json \
        --type dental \
        --profile uo-innovation
"""

import argparse
import json
import sys
from decimal import Decimal
import boto3
from botocore.exceptions import ClientError


def to_decimal(obj):
    """Recursively convert floats to Decimal for DynamoDB."""
    if isinstance(obj, float):
        return Decimal(str(obj))
    if isinstance(obj, dict):
        return {k: to_decimal(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [to_decimal(i) for i in obj]
    return obj


def get_dynamodb(profile, region):
    session = boto3.Session(profile_name=profile, region_name=region)
    return session.resource('dynamodb')


def upload_patients(records, dynamodb, table_prefix):
    patients_table = dynamodb.Table(f'{table_prefix}-patients')
    diagnoses_table = dynamodb.Table(f'{table_prefix}-diagnoses')
    medications_table = dynamodb.Table(f'{table_prefix}-medications')
    patient_diagnoses_table = dynamodb.Table(f'{table_prefix}-patient-diagnoses')
    patient_medications_table = dynamodb.Table(f'{table_prefix}-patient-medications')

    seen_diagnoses = {}
    seen_medications = {}
    patient_count = pd_count = pm_count = 0

    print(f"Uploading {len(records)} patient records...")

    with patients_table.batch_writer() as batch:
        for p in records:
            demo = p.get("demographics", {})
            metrics = p.get("health_metrics", {})
            item = to_decimal({
                "patient_id": p["patient_id"],
                "age": demo.get("age"),
                "gender": demo.get("gender"),
                "race": demo.get("race"),
                "bmi": metrics.get("bmi"),
                "last_updated": p.get("last_updated", ""),
            })
            item = {k: v for k, v in item.items() if v is not None}
            batch.put_item(Item=item)
            patient_count += 1
    print(f"  ✓ {patient_count} patients uploaded")

    for p in records:
        for d in p.get("diagnoses", []):
            code = d.get("code")
            if code and code not in seen_diagnoses:
                seen_diagnoses[code] = d
        for m in p.get("medications", []):
            name = m.get("name")
            if name and name not in seen_medications:
                seen_medications[name] = m

    with diagnoses_table.batch_writer() as batch:
        for code, d in seen_diagnoses.items():
            batch.put_item(Item=to_decimal({
                "diagnosis_code": code,
                "name": d.get("description", code),
                "category": d.get("status", "active"),
            }))
    print(f"  ✓ {len(seen_diagnoses)} unique diagnoses uploaded")

    with medications_table.batch_writer() as batch:
        for name, m in seen_medications.items():
            batch.put_item(Item=to_decimal({
                "medication_id": name.upper().replace(" ", "_"),
                "name": name,
                "dosage": m.get("dosage", ""),
            }))
    print(f"  ✓ {len(seen_medications)} unique medications uploaded")

    with patient_diagnoses_table.batch_writer() as batch:
        for p in records:
            for d in p.get("diagnoses", []):
                code = d.get("code")
                if not code:
                    continue
                batch.put_item(Item=to_decimal({
                    "patient_id": p["patient_id"],
                    "diagnosis_code": code,
                    "onset_date": d.get("onset_date", ""),
                    "status": d.get("status", ""),
                }))
                pd_count += 1
    print(f"  ✓ {pd_count} patient-diagnosis links uploaded")

    with patient_medications_table.batch_writer() as batch:
        for p in records:
            for m in p.get("medications", []):
                name = m.get("name")
                if not name:
                    continue
                batch.put_item(Item=to_decimal({
                    "patient_id": p["patient_id"],
                    "medication_id": name.upper().replace(" ", "_"),
                    "medication_name": name,
                    "dosage": m.get("dosage", ""),
                    "start_date": m.get("start_date", ""),
                }))
                pm_count += 1
    print(f"  ✓ {pm_count} patient-medication links uploaded")


def ensure_dental_table(dynamodb, table_name):
    try:
        table = dynamodb.create_table(
            TableName=table_name,
            KeySchema=[{"AttributeName": "visit_id", "KeyType": "HASH"}],
            AttributeDefinitions=[{"AttributeName": "visit_id", "AttributeType": "S"}],
            BillingMode="PAY_PER_REQUEST",
        )
        table.wait_until_exists()
        print(f"  ✓ Created table {table_name}")
        return table
    except ClientError as e:
        if e.response["Error"]["Code"] == "ResourceInUseException":
            print(f"  ✓ Table {table_name} already exists")
            return dynamodb.Table(table_name)
        raise


def upload_dental(records, dynamodb, table_prefix):
    table_name = f'{table_prefix}-dental-visits'
    table = ensure_dental_table(dynamodb, table_name)
    print(f"Uploading {len(records)} dental visit records...")
    visit_count = 0
    with table.batch_writer() as batch:
        for v in records:
            item = to_decimal({
                "visit_id": v["visit_id"],
                "patient_id": v.get("patient_id", ""),
                "visit_date": v.get("visit_date", ""),
                "provider_id": v.get("provider_id", ""),
                "chief_complaint": v.get("examination", {}).get("chief_complaint", ""),
                "oral_hygiene_index": v.get("examination", {}).get("oral_hygiene_index"),
            })
            item = {k: val for k, val in item.items() if val is not None and val != ""}
            batch.put_item(Item=item)
            visit_count += 1
    print(f"  ✓ {visit_count} dental visits uploaded")


def verify(dynamodb, table_prefix, record_type):
    print("\nVerification:")
    if record_type == "patient":
        suffixes = ["patients", "diagnoses", "medications", "patient-diagnoses", "patient-medications"]
    else:
        suffixes = ["dental-visits"]
    for suffix in suffixes:
        try:
            resp = dynamodb.Table(f'{table_prefix}-{suffix}').scan(Select="COUNT")
            print(f"  {table_prefix}-{suffix}: {resp['Count']} records")
        except Exception:
            print(f"  {table_prefix}-{suffix}: (could not scan)")


def main():
    parser = argparse.ArgumentParser(description="Upload synthetic healthcare data to DynamoDB")
    parser.add_argument("--json-file", required=True, help="Path to generated JSON file")
    parser.add_argument("--type", required=True, choices=["patient", "dental"],
                        help="Record type: patient or dental")
    parser.add_argument("--profile", default=None, help="AWS profile (e.g. uo-innovation)")
    parser.add_argument("--region", default="us-west-2", help="AWS region")
    parser.add_argument("--table-prefix", default="healthcare", help="DynamoDB table prefix")
    args = parser.parse_args()

    print("Healthcare Data Upload")
    print("=" * 50)
    print(f"  File  : {args.json_file}")
    print(f"  Type  : {args.type}")
    print(f"  Region: {args.region}")
    print(f"  Tables: {args.table_prefix}-*")
    print()

    try:
        with open(args.json_file) as f:
            records = json.load(f)
    except FileNotFoundError:
        print(f"Error: File not found: {args.json_file}")
        print("Generate it first:")
        print("  cd module-5-synthetic-data/generators && python generate_patient_data.py")
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON — {e}")
        sys.exit(1)

    try:
        dynamodb = get_dynamodb(args.profile, args.region)
        if args.type == "patient":
            upload_patients(records, dynamodb, args.table_prefix)
        else:
            upload_dental(records, dynamodb, args.table_prefix)
        verify(dynamodb, args.table_prefix, args.type)
        print("\nDone!")
    except Exception as e:
        print(f"\nError: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
