#!/bin/bash

#####################################################################
# AWS Credentials Setup
# Configures AWS credentials and writes .env for deploy-all.sh
#####################################################################

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

clear
echo -e "${BOLD}${CYAN}============================================${NC}"
echo -e "${BOLD}${CYAN}   AWS Credentials Setup${NC}"
echo -e "${BOLD}${CYAN}============================================${NC}"
echo ""

# Check if AWS CLI is installed
if ! command -v aws &> /dev/null; then
    echo -e "${RED}✗ AWS CLI not found!${NC}"
    echo ""
    echo "Please install AWS CLI first:"
    echo ""
    echo "macOS:   brew install awscli"
    echo "Linux:   https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html"
    echo "Windows: https://aws.amazon.com/cli/"
    echo ""
    exit 1
fi
echo -e "${GREEN}✓ AWS CLI installed${NC}"
echo ""

# ============================================================
# Helper: write_env
# Writes the full .env file given a profile name, account ID,
# region, and student ID. Called from all four auth paths so
# the generated file is always identical in structure.
#
# Centralised .env generation so options 1 and 4 (which
# previously never wrote .env) and options 2 and 3 all
# produce the same file with the same variables.
# ============================================================
write_env() {
    local profile="$1"
    local account_id="$2"
    local region="$3"
    local student_id="$4"

    cat > "${SCRIPT_DIR}/.env" <<EOF
# Healthcare AI Infrastructure Configuration
# Auto-generated by setup-aws-credentials.sh on $(date)
# Edit and re-run setup-aws-credentials.sh to regenerate.

# ============================================
# AWS Identity
# ============================================
AWS_PROFILE=${profile}
AWS_REGION=${region}
AWS_ACCOUNT_ID=${account_id}

# ============================================
# Student Information
# ============================================
STUDENT_ID=${student_id}

# ============================================
# EKS Cluster Configuration
# ============================================
CLUSTER_NAME=ollama-ai-cluster
K8S_VERSION=1.35

# ============================================
# GPU Configuration
#
# USE_GPU=true  → g4dn.xlarge, ~30 tokens/s, ~\$20-25/day
#                 Required for live classroom demos.
#
# USE_GPU=false → t3.xlarge CPU-only, ~4 tokens/s, ~\$8-12/day
#                 Acceptable for self-paced assignments.
#
# Recommended for classroom use: USE_GPU=true
# ============================================
USE_GPU=true
GPU_NODE_COUNT=1
GPU_INSTANCE_TYPE=g4dn.xlarge

# ============================================
# Ollama Configuration
# ============================================
OLLAMA_NAMESPACE=ollama
OLLAMA_REPLICAS=1
STORAGE_SIZE=50Gi
OLLAMA_VERSION=latest

# ============================================
# AWS Bedrock Configuration
# ============================================
BEDROCK_REGION=${region}
BEDROCK_MODEL=anthropic.claude-3-haiku-20240307-v1:0
USE_BEDROCK=true

# ============================================
# DynamoDB Configuration
# ============================================
TABLE_PREFIX=healthcare
BILLING_MODE=PAY_PER_REQUEST

# ============================================
# Integration Service Configuration
# ============================================
INTEGRATION_NAMESPACE=ollama
IMAGE_NAME=healthcare-ai-bridge
IMAGE_TAG=latest

# ============================================
# S3 Storage
# Leave blank — auto-generated from account ID
# by 5-setup-s3-storage.sh.
# ============================================
S3_BUCKET_NAME=
S3_EXPORT_ENABLED=true
EOF

    echo -e "${GREEN}✓ Created .env${NC}"
}

# ============================================================
# Helper: prompt_student_id
# Prompts for DuckID so it can be written into .env.
#
# Previously .env left STUDENT_ID commented out, causing
# deploy-all.sh to prompt again mid-run. Capturing it here
# means students only enter it once.
# ============================================================
prompt_student_id() {
    echo ""
    read -p "Enter your DuckID (e.g., wgoodson): " STUDENT_ID
    if [ -z "$STUDENT_ID" ]; then
        echo -e "${RED}✗ DuckID is required${NC}"
        exit 1
    fi
    echo -e "${GREEN}✓ Student ID: ${STUDENT_ID}${NC}"
}

# ============================================================
# Check if credentials are already configured
#
# Original used bare aws sts get-caller-identity without
# --profile, which would succeed on the default profile
# even if uo-innovation wasn't configured yet.
# ============================================================
echo -e "${BLUE}Checking current AWS configuration...${NC}"
echo ""

if aws sts get-caller-identity --profile uo-innovation &> /dev/null; then
    echo -e "${GREEN}✓ uo-innovation profile is already configured!${NC}"
    echo ""
    CURRENT_ACCOUNT=$(aws sts get-caller-identity --profile uo-innovation --query Account --output text 2>/dev/null)
    CURRENT_USER=$(aws sts get-caller-identity --profile uo-innovation --query Arn --output text 2>/dev/null)
    CURRENT_REGION=$(aws configure get region --profile uo-innovation 2>/dev/null || echo "us-west-2")

    echo "Current Configuration:"
    echo "  Account ID: ${CURRENT_ACCOUNT}"
    echo "  User/Role:  ${CURRENT_USER}"
    echo "  Region:     ${CURRENT_REGION}"
    echo ""

    read -p "Do you want to use this configuration? (yes/no): " -r
    if [[ $REPLY =~ ^[Yy](es)?$ ]]; then
        prompt_student_id
        write_env "uo-innovation" "$CURRENT_ACCOUNT" "$CURRENT_REGION" "$STUDENT_ID"
        echo ""
        echo "You're ready to deploy! Run: source .env && ./deploy-all.sh"
        exit 0
    fi
fi

echo -e "${YELLOW}Configuring AWS credentials...${NC}"
echo ""

# ============================================================
# Auth method selection
# ============================================================
echo -e "${BOLD}AWS Authentication Options:${NC}"
echo ""
echo "1. IAM User (Access Key + Secret Key)"
echo "2. Federated/SSO Account (Recommended for UO Innovation Sandbox)"
echo "3. AWS Named Profile (Use existing profile)"
echo "4. Environment Variables (Temporary credentials)"
echo ""
read -p "Select option (1-4): " AUTH_OPTION

case $AUTH_OPTION in

    # --------------------------------------------------------
    1)  # IAM User
    # --------------------------------------------------------
        echo ""
        echo -e "${BOLD}${BLUE}Setting up IAM User credentials${NC}"
        echo ""
        echo "You'll need your AWS Access Key ID and Secret Access Key."
        echo "To create these: AWS Console → IAM → Users → Your User"
        echo "  → Security credentials → Create access key"
        echo ""
        read -p "Press Enter when you have your keys ready..."
        echo ""

        read -p "Enter AWS Access Key ID: " ACCESS_KEY
        read -s -p "Enter AWS Secret Access Key: " SECRET_KEY
        echo ""
        read -p "Enter default region [us-west-2]: " INPUT_REGION
        AWS_REGION="${INPUT_REGION:-us-west-2}"
        echo ""

        aws configure set aws_access_key_id "$ACCESS_KEY" --profile uo-innovation
        aws configure set aws_secret_access_key "$SECRET_KEY" --profile uo-innovation
        aws configure set region "$AWS_REGION" --profile uo-innovation
        aws configure set output json --profile uo-innovation

        if aws sts get-caller-identity --profile uo-innovation &> /dev/null; then
            echo -e "${GREEN}✓ AWS credentials configured successfully!${NC}"
            ACCOUNT_ID=$(aws sts get-caller-identity --profile uo-innovation --query Account --output text)
            echo "  Account ID: ${ACCOUNT_ID}"
            prompt_student_id
            write_env "uo-innovation" "$ACCOUNT_ID" "$AWS_REGION" "$STUDENT_ID"
        else
            echo -e "${RED}✗ Failed to verify credentials. Please check and try again.${NC}"
            exit 1
        fi
        ;;

    # --------------------------------------------------------
    2)  # Federated/SSO
    # --------------------------------------------------------
        echo ""
        echo -e "${BOLD}${BLUE}Setting up Federated/SSO Account${NC}"
        echo ""
        echo "If you haven't configured SSO yet:"
        echo "  aws configure sso"
        echo "  aws sso login --profile YOUR_PROFILE_NAME"
        echo ""
        read -p "Have you completed SSO setup? (yes/no): " -r

        if [[ ! $REPLY =~ ^[Yy](es)?$ ]]; then
            echo ""
            echo "Please complete SSO setup first, then run this script again."
            exit 1
        fi

        echo ""
        echo "Available profiles:"
        aws configure list-profiles 2>/dev/null || echo "  (no profiles found)"
        echo ""
        read -p "Enter your AWS SSO profile name: " SSO_PROFILE

        if aws sts get-caller-identity --profile "$SSO_PROFILE" &> /dev/null; then
            echo -e "${GREEN}✓ SSO profile verified!${NC}"

            ACCOUNT_ID=$(aws sts get-caller-identity --profile "$SSO_PROFILE" --query Account --output text)
            REGION=$(aws configure get region --profile "$SSO_PROFILE" 2>/dev/null || echo "us-west-2")

            # If the SSO profile isn't named uo-innovation, create an alias
            if [ "$SSO_PROFILE" != "uo-innovation" ]; then
                echo ""
                echo -e "${YELLOW}Note: Scripts require a profile named 'uo-innovation'.${NC}"
                echo "Creating uo-innovation as an alias for ${SSO_PROFILE}..."
                ACCESS_KEY_ID=$(aws configure get aws_access_key_id --profile "$SSO_PROFILE" 2>/dev/null || true)
                SECRET_KEY=$(aws configure get aws_secret_access_key --profile "$SSO_PROFILE" 2>/dev/null || true)
                SESSION_TOKEN=$(aws configure get aws_session_token --profile "$SSO_PROFILE" 2>/dev/null || true)
                SSO_START=$(aws configure get sso_start_url --profile "$SSO_PROFILE" 2>/dev/null || true)

                if [ -n "$SSO_START" ]; then
                    # SSO profile — copy SSO config fields
                    SSO_REGION=$(aws configure get sso_region --profile "$SSO_PROFILE" 2>/dev/null)
                    SSO_ACCOUNT=$(aws configure get sso_account_id --profile "$SSO_PROFILE" 2>/dev/null)
                    SSO_ROLE=$(aws configure get sso_role_name --profile "$SSO_PROFILE" 2>/dev/null)
                    aws configure set sso_start_url "$SSO_START" --profile uo-innovation
                    aws configure set sso_region "$SSO_REGION" --profile uo-innovation
                    aws configure set sso_account_id "$SSO_ACCOUNT" --profile uo-innovation
                    aws configure set sso_role_name "$SSO_ROLE" --profile uo-innovation
                    aws configure set region "$REGION" --profile uo-innovation
                    aws configure set output json --profile uo-innovation
                    echo -e "${GREEN}✓ Created uo-innovation SSO profile${NC}"
                    echo "  You may need to run: aws sso login --profile uo-innovation"
                fi
            fi

            prompt_student_id
            write_env "uo-innovation" "$ACCOUNT_ID" "$REGION" "$STUDENT_ID"
        else
            echo -e "${YELLOW}⚠ Could not verify profile. You may need to login first:${NC}"
            echo "  aws sso login --profile $SSO_PROFILE"
            exit 1
        fi
        ;;

    # --------------------------------------------------------
    3)  # Named Profile
    # --------------------------------------------------------
        echo ""
        echo -e "${BOLD}${BLUE}Using AWS Named Profile${NC}"
        echo ""
        echo "Available profiles:"
        aws configure list-profiles 2>/dev/null || echo "  (no profiles found)"
        echo ""
        read -p "Enter profile name to use: " PROFILE_NAME

        if aws sts get-caller-identity --profile "$PROFILE_NAME" &> /dev/null; then
            echo -e "${GREEN}✓ Profile verified!${NC}"

            ACCOUNT_ID=$(aws sts get-caller-identity --profile "$PROFILE_NAME" --query Account --output text)
            REGION=$(aws configure get region --profile "$PROFILE_NAME" 2>/dev/null || echo "us-west-2")

            # Create uo-innovation alias if needed
            if [ "$PROFILE_NAME" != "uo-innovation" ]; then
                echo ""
                echo -e "${YELLOW}Note: Scripts require a profile named 'uo-innovation'.${NC}"
                echo "Creating uo-innovation as a copy of ${PROFILE_NAME}..."
                ACCESS_KEY_ID=$(aws configure get aws_access_key_id --profile "$PROFILE_NAME" 2>/dev/null || true)
                SECRET_KEY=$(aws configure get aws_secret_access_key --profile "$PROFILE_NAME" 2>/dev/null || true)
                SESSION_TOKEN=$(aws configure get aws_session_token --profile "$PROFILE_NAME" 2>/dev/null || true)
                if [ -n "$ACCESS_KEY_ID" ]; then
                    aws configure set aws_access_key_id "$ACCESS_KEY_ID" --profile uo-innovation
                    aws configure set aws_secret_access_key "$SECRET_KEY" --profile uo-innovation
                    [ -n "$SESSION_TOKEN" ] && aws configure set aws_session_token "$SESSION_TOKEN" --profile uo-innovation
                    aws configure set region "$REGION" --profile uo-innovation
                    aws configure set output json --profile uo-innovation
                    echo -e "${GREEN}✓ Created uo-innovation profile${NC}"
                else
                    echo -e "${YELLOW}⚠ Could not copy credentials automatically.${NC}"
                    echo "  Please manually configure: aws configure --profile uo-innovation"
                fi
            fi

            prompt_student_id
            write_env "uo-innovation" "$ACCOUNT_ID" "$REGION" "$STUDENT_ID"
        else
            echo -e "${RED}✗ Could not access profile: $PROFILE_NAME${NC}"
            exit 1
        fi
        ;;

    # --------------------------------------------------------
    4)  # Environment Variables
    # FIX: Option 4 previously never wrote .env. Now verifies
    #      env var credentials and calls write_env.
    # --------------------------------------------------------
        echo ""
        echo -e "${BOLD}${BLUE}Using Environment Variables${NC}"
        echo ""
        echo "Set these before running this script:"
        echo "  export AWS_ACCESS_KEY_ID=YOUR_ACCESS_KEY"
        echo "  export AWS_SECRET_ACCESS_KEY=YOUR_SECRET_KEY"
        echo "  export AWS_SESSION_TOKEN=YOUR_SESSION_TOKEN  # if using temporary creds"
        echo "  export AWS_REGION=us-west-2"
        echo ""
        read -p "Have you set these variables? (yes/no): " -r

        if [[ ! $REPLY =~ ^[Yy](es)?$ ]]; then
            echo "Please set environment variables and try again."
            exit 1
        fi

        if aws sts get-caller-identity &> /dev/null; then
            echo -e "${GREEN}✓ Environment credentials verified!${NC}"

            ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
            REGION="${AWS_REGION:-us-west-2}"

            # Write credentials into uo-innovation profile so scripts can
            # use --profile uo-innovation consistently
            aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID" --profile uo-innovation
            aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY" --profile uo-innovation
            [ -n "$AWS_SESSION_TOKEN" ] && \
                aws configure set aws_session_token "$AWS_SESSION_TOKEN" --profile uo-innovation
            aws configure set region "$REGION" --profile uo-innovation
            aws configure set output json --profile uo-innovation
            echo -e "${GREEN}✓ Saved credentials to uo-innovation profile${NC}"

            prompt_student_id
            write_env "uo-innovation" "$ACCOUNT_ID" "$REGION" "$STUDENT_ID"
        else
            echo -e "${RED}✗ Could not verify environment credentials${NC}"
            exit 1
        fi
        ;;

    *)
        echo -e "${RED}Invalid option${NC}"
        exit 1
        ;;
esac

# ============================================================
# Final verification and permission checks
# FIX: All checks now use --profile uo-innovation consistently.
#      Fixed broken iam case (was printing text instead of
#      checking IAM). Added bedrock check. ACCOUNT_ID and
#      REGION are always set before reaching this point.
# ============================================================
echo ""
echo -e "${BOLD}${CYAN}============================================${NC}"
echo -e "${BOLD}${CYAN}   Verifying AWS Access${NC}"
echo -e "${BOLD}${CYAN}============================================${NC}"
echo ""

FINAL_ACCOUNT=$(aws sts get-caller-identity --profile uo-innovation --query Account --output text 2>/dev/null)
FINAL_ARN=$(aws sts get-caller-identity --profile uo-innovation --query Arn --output text 2>/dev/null)
FINAL_REGION=$(aws configure get region --profile uo-innovation 2>/dev/null || echo "us-west-2")

if [ -z "$FINAL_ACCOUNT" ]; then
    echo -e "${RED}✗ Could not verify AWS access via uo-innovation profile${NC}"
    exit 1
fi

echo -e "${GREEN}✓ AWS credentials are working!${NC}"
echo ""
echo "Configuration Summary:"
echo "  Account ID: ${FINAL_ACCOUNT}"
echo "  Identity:   ${FINAL_ARN}"
echo "  Region:     ${FINAL_REGION}"
echo ""

echo "Checking service permissions..."
echo ""
ALL_GOOD=true

check_permission() {
    local label="$1"
    local required="$2"
    shift 2
    if "$@" &> /dev/null; then
        echo -e "  ${GREEN}✓${NC} ${label}"
    else
        if [ "$required" = "required" ]; then
            echo -e "  ${RED}✗${NC} ${label} (required)"
            ALL_GOOD=false
        else
            echo -e "  ${YELLOW}⚠${NC} ${label} (optional — may need activation)"
        fi
    fi
}

check_permission "EKS access" "required" \
    aws eks list-clusters --region "$FINAL_REGION" --profile uo-innovation

check_permission "EC2 access" "required" \
    aws ec2 describe-vpcs --region "$FINAL_REGION" --profile uo-innovation

check_permission "DynamoDB access" "required" \
    aws dynamodb list-tables --region "$FINAL_REGION" --profile uo-innovation

check_permission "S3 access" "required" \
    aws s3 ls --profile uo-innovation

check_permission "IAM access" "required" \
    aws iam get-user --profile uo-innovation

check_permission "Bedrock access" "optional" \
    aws bedrock list-foundation-models --region "$FINAL_REGION" --profile uo-innovation

echo ""

if [ "$ALL_GOOD" = true ]; then
    echo -e "${GREEN}✓ All required permissions verified!${NC}"
else
    echo -e "${YELLOW}⚠ Some required permissions are missing.${NC}"
    echo ""
    echo "Contact your AWS admin with:"
    echo "  Account: ${FINAL_ACCOUNT}"
    echo "  User:    ${FINAL_ARN}"
    echo "  Needed:  EKS, EC2, DynamoDB, S3, IAM permissions"
fi

echo ""
echo -e "${BOLD}Next steps:${NC}"
echo ""
echo "  1. Source your environment:"
echo "     source .env"
echo ""
echo "  2. Run deployment:"
echo "     ./deploy-all.sh"
echo ""